import { Inter } from "next/font/google";
import "./globals.css";
import {GlobalContextProvider} from "@/app/state-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <GlobalContextProvider>
      <body className={inter.className}>{children}</body>
    </GlobalContextProvider>
    </html>
  );
}
